---
title: "Exploring Quarto and Latex"
author: "Grace Juan"
format: pdf
editor: visual
number-sections: true
editor_options: 
  chunk_output_type: console
---

##Integration by Substitution

::: {#htm:subrule}
## Substitution Rule

If $u=g(x)$ is a differentiable function whose range is an interval $I$ and $f$ is a continuous on $I$ then,

$$
\int f(g(x))\cdot g'(x)dx = \int f(u)du
$$
:::

::: {exm:subrule}
1.$\int \left(1-4x\right)^\frac{1}{2}dx$

If we let $u=1-4x$, then $du=-4dx$. We multiply the integrand $\frac{-4}{-4}$. Thus, $$
\int \left(1-4x\right)^\frac{1}{2}dx = \int \left(1-4x\right)^\frac{1}{2}\cdot \frac{-4}{-4}dx = \int u^\frac{1}{2} \left( -\frac{du}{4} \right)= -\frac{1}{4} \int u^\frac{1}{2} du = -\frac{1}{4}\cdot \frac{2u^\frac{3}{2}}{3} + C. $$

We put the final answer in terms of $x$ by substituting $u=1-4x$. Therefore, $$
\int \left(1-4x\right)^\frac{1}{2} dx = \frac{\left(1-4x\right)^\frac{3}{2}}{6} + C.$$

2.$\int x^2\left(x^3-1\right)^{10} dx$

Let $u=x^3-1$. Then $du=3x^2dx$, or $\frac{du}{3}=x^2 dx$. By substitution, $$
\int x^2\left(x^3-1\right)^{10} dx = \int u^{10}\cdot \frac{du}{3}= \frac{1}{3}\int u^{10}du=\frac{u^{11}}{33} + C= \frac{\left(x^3-1\right)^{11}}{33}+ C.
$$

3.$\int \frac{x}{\left(x^2+1\right)^3} dx$

Let $u=x^2+1$. Then $du=2xdx$, or $\frac{du}{2}=xdx$. By substitution, $$
\int \frac{x}{\left(x^2+1\right)^3}dx=\frac{1}{2}\int u^{-3}du=\frac{1}{2}\cdot \frac{u^{-2}}{-2}+C=-\frac{1}{4\left(x^2+1\right)^2}+C.
$$

4.$\int cos^4 xsinxdx$

Let $u=cos x$. Then $du=-sinxdx$, or $-du=sinxdx$. By substitution, $$
\int cos^4 xsinxdx=-\int u^4 du=-\frac{u^5}{5}+C=-\frac{cos^5 x}{5}+C.
$$

5.$\int xsec^3 \left( x^2 \right)tan\left(x^2\right)dx$

Let $u=sec\left(x^2\right)$. Then $du=sec\left(x^2\right)tan\left(x^2\right)\cdot 2xdx$, or $\frac{du}{2}=sec\left(x^2\right)tan\left(x^2\right)\cdot xdx$. By substitution, $$
\int xsec^3 \left(x^2\right)tan\left(x^2\right)dx = \int sec^2 \left(x^2\right)sec\left(x^2\right)tan\left(x^2\right)\cdot xdx=\int u^2du=\frac{1}{2}\cdot \frac{u^3}{3}+C=\frac{sec^3 \left(x^2\right)}{6} + C.
$$

6.\$\int tan\frac{1}{s}+tan\frac{1}{s}sin\frac{1}{s}

7.$\int t\sqrt {t-1} dt$

Let $u=t-1$. Then $u=dt$. Also, $t=u+1$. By substitution, $$
\int t\sqrt{t-1} dt=\int \left(u+1\right)u^\frac{1}{2}du=\int \left( u^\frac{3}{2}+u^\frac{1}{2} \right)du=\frac{2u^\frac{5}{2}}{5}+\frac{2u^\frac{3}{2}}{3}+C=\frac{2\left(t-1\right)^\frac{5}{2}}{5}+\frac{2\left(t-1\right)^\frac{3}{2}}{3}+C.
$$

8.$\int \frac{t^3}{\sqrt{t^2+3}}dt$

Let $u=t^2+3$. Then $du=2tdt$, or $\frac{du}{2}=tdt$. Also, $t^2=u-3$. By substitution, 
$$
\int \frac{t^3}{\sqrt{t^2+3}}dt=\int \frac{t^2\cdot{t}}{\sqrt {t^2+3}}dt=\int u^\frac{-1}{2}(u-3)\frac{du}{2}=\frac{1}{2}\int \left(u^\frac{1}{2}-3u^\frac{-1}{2}\right)du=\frac{1}{2} \left(\frac{2u^\frac{3}{2}}{3}-6u^\frac{1}{2}\right)+C=\frac{\left(t^2+3\right)^\frac{3}{2}}{3}-3\left(t^2+3\right)^\frac{1}{2}+C. 
$$

9.$\int \sqrt{4+\sqrt x}dx$




:::
